language: java
sudo: true
os: linux
jdk: oraclejdk8

script: 
  - echo "Installing dependencies..."
  - cd dependencies
  - sh install.sh
  - echo "Done."
  - cd ../java-project 
  - mvn clean verify

cache:
 directories:
  - $HOME/.m2
